### PR TITLE
Use consistent domain with auth url

### PR DESCRIPTION
**Pull request by toy**

### CODE REVIEW

**Comment by maxlaverse** [comment]
hi @toy ,
This was meant to give a hint to users that the domain extension might be different from the portal URL. I had feedback at the beginning regarding this, because people were using the same extension and complaining their credentials wouldn't work. Do you have another idea how to do it ?

**Comment by toy** [comment]
Good point, then not sure, maybe `company.tld` or leave it as is

**Comment by maxlaverse** [comment]
Great ! Thanks. Let's try and see

**Comment by maxlaverse** [comment]
I think I'll roll it back for now, and prepare something to scrape the domain list from the portal itself

**Comment by toy** [comment]
Will be the best solution

**Pull request merged**
